### ISSUE TITLE
The data links are changed by NCBI

### ISSUE THREAD

**Issue by bevar** [genome-in-a-bottle/giab_data_indexes#1]
The **ftp** links in this projects(eg: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data) are changed to **https** protocol(thus https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data will be the correct link). It confused me a lot.

**Comment by chunlinxiao** [comment]
As far as I know there is no change for ftp link - it should work as before.  

But if you used http protocol, then you have to change to https now.

Hope this helps.

**Comment by bevar** [comment]
OK, thanks.
