### ISSUE TITLE
Incorrect link to PacBio CLR data for HG004

### ISSUE THREAD

**Issue by AndrewCarroll** [genome-in-a-bottle/giab_data_indexes#11]
This is a minor issue. It looks like the link listed in the main table for the PacBio CLR data of HG004 points to the wrong location.

The link points to: `https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/AshkenazimTrio/sequence.index.AJtrio_PacBio_MtSinai_NIST_subreads_fasta_10082018.HG004`

and this file is not present. There is a link in the manifest that appears to be correct for HG004 at the following location:

`https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/AshkenazimTrio/sequence.index.AJtrio_PacBio_MtSinai_NIST_subreads_fasta_10052018.HG004`

It may be that this link just needs to be updated.

**Comment by chunlinxiao** [comment]
thanks Andrew - I'll take a look at this.

**Comment by chunlinxiao** [comment]
now the file https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/AshkenazimTrio/sequence.index.AJtrio_PacBio_MtSinai_NIST_subreads_fasta_10082018.HG004 is there.  Thanks

**Comment by AndrewCarroll** [comment]
Thank you!
