### ISSUE TITLE
raw data  between 30X and 40X and their truth VCF

### ISSUE THREAD

**Issue by Talo07** [genome-in-a-bottle/giab_data_indexes#14]
Dear GIAB team,

I just discovered these wonderful data (singleton and trio) to evaluate my variant call pipeline.

Maybe a stupid request, would it be possible to send me a raw data link (ilumina fastq) with coverage between 30X and 40X and their truth vcf results done on hg38. My human genome WGS samples having a coverage between 30x and 40x that's why I am requesting the raw data from this coverage.
I also wanted to know if I was using the reference hg38.fasta from UCSC will not affect the comparison with vcf truth.

I would be very grateful and Thanks in advance !

**Comment by jzook** [comment]
The easiest place to get 35x fastq files for HG002/HG003/HG004 may be from the recent precisionFDA challenge data under https://doi.org/10.18434/mds2-2336. This challenge and descriptions of comparisons done to the benchmark are described in https://doi.org/10.1101/2020.11.13.380741. The latest v4.2.1 GRCh38 benchmarks ("truth" vcfs and beds) for this trio are under ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/AshkenazimTrio, described in https://doi.org/10.1101/2020.07.24.212712%20. Using hg38.fasta from UCSC should be fine. Cheers!

**Comment by Talo07** [comment]
Thank you for your answer @jzook , it is very useful for me. I have singleton samples and I would like to know if you have any idea to take the fastq of HG001 (30X-40X) .

Otherwise, can I only use HG002 to use it as a singleton because as you know it is among the trio?
