### ISSUE TITLE
Raw PacBio subreads data

### ISSUE THREAD

**Issue by PengNi** [genome-in-a-bottle/giab_data_indexes#15]
Dear GIAB team,

Thanks for the wonderful data collection.
Maybe an inappropriate question, would it be possible to access the raw PacBio SequelII CCS 11kb data of NA12878 (or other samples), _i.e._, `subreads.bam` with IPD and other information in it?

Thank you in advance!

Best,
Peng

**Comment by jzook** [comment]
Dear Peng,

More recent raw 15kb and 24kb HiFi data for HG002 from PacBio for the DeepConsensus paper is at https://console.cloud.google.com/storage/browser/brain-genomics-public/research/deepconsensus/publication/sequencing;tab=objects?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

Cheers,
Justin

**Comment by PengNi** [comment]
@jzook , awesome! Thank you for telling me! I will have a try.

Best,
Peng
