### ISSUE TITLE
Missing BED files for exome fastqs

### ISSUE THREAD

**Issue by vladimirkovacevic** [genome-in-a-bottle/giab_data_indexes#2]
Do you have available capture BED files for [NA12878_Illumina_HiSeq_Exome_Garvan_trimmed_fastq_09252015](https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/NA12878/sequence.index.NA12878_Illumina_HiSeq_Exome_Garvan_trimmed_fastq_09252015)?

**Comment by uros-sb** [comment]
Is this BED for assembly 37 or 38?

**Comment by chunlinxiao** [comment]
the README file does not mention whether this data is b37 or b38 based; but the vcf file project.NIST.hc.snps.indels.vcf  clearly mentioned hg19/grch37 in the header as below:

##contig=<ID=chr1,length=249250621,assembly=hg19>

**Comment by uros-sb** [comment]
Yeah great, thank you for answering 3 years later :)
