### ISSUE TITLE
Missing Bed files for Illumina Whole Exome by Oslo Uni. Hospital 

### ISSUE THREAD

**Issue by shexuan** [genome-in-a-bottle/giab_data_indexes#4]
Do you have avaliable capture bed files of [HG002、HG003、HG004](https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/AshkenazimTrio/alignment.index.AJtrio_OsloUniversityHospital_IlluminaExome_bwamem_GRCh37_11252015)
[HG005](https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/ChineseTrio/alignment.index.Chinesetrio_HG005_OsloUniversityHospital_IlluminaExome_bwamem_GRCh37_11252015)?

**Comment by shexuan** [comment]
And the md5sum for ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/OsloUniversityHospital_Exome/151002_7001448_0359_AC7F6GANXX_Sample_HG002-EEogPU_v02-KIT-Av5_AGATGTAC_L008.posiSrt.markDup.bai is wrong. Please check it.

**Comment by jzook** [comment]
The capture file is under
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/analysis/OsloUniversityHospital_Exome_GATK_jointVC_11242015/

The md5sum for the bai file should be d4fea426c3e2e9a71bb92e6526b4df6f.  Is this what you have?

**Comment by shexuan** [comment]
@jzook  Yes, that's what I get.  But [Here](https://github.com/genome-in-a-bottle/giab_data_indexes/blob/master/AshkenazimTrio/alignment.index.AJtrio_OsloUniversityHospital_IlluminaExome_bwamem_GRCh37_11252015) is wrong, it's the same as the corresponding bam file. And thanks for the bed files.

**Comment by jzook** [comment]
Thanks, @shexuan!  @chunlinxiao, could you take a look at the link to which shexuan refers?  Thanks!

**Comment by chunlinxiao** [comment]
Just noticed that this email sit in Junk folder – I will take a look the file.

Thanks


chunlin

**Comment by chunlinxiao** [comment]
the md5 for the bai is fixed.  thanks shexun.

chunlin

**Comment by chunlinxiao** [comment]
I'm closing this one.
