### ISSUE TITLE
Data descriptions for newer data

### ISSUE THREAD

**Issue by anands-repo** [genome-in-a-bottle/giab_data_indexes#6]
Hi,

Data descriptions for some of the raw data is greatly appreciated. Specifically, I am looking for information regarding
1. Alignment method/any error correction used over raw subreads for alignments in ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_MtSinai_NIST/Baylor_NGMLR_bam_GRCh37/
2. Description of sequencing method used for ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NA12878_PacBio_MtSinai/. Is it the same as that for HG002 (which is described in the original publication - https://www.nature.com/articles/sdata201625)?

Thanks!

**Comment by fritzsedlazeck** [comment]
Hi,
for point 1: no raw read correction was done. 

point2: yes it is. Its an older set of Pacbio sequencing run I think even on RS2 from back then.

Thanks
Fritz

**Comment by anands-repo** [comment]
No further questions. Thanks!

**Comment by fritzsedlazeck** [comment]
You mean for the SV calls ? We do have the SNV release under review right now. 
SV calls is not a new release expected.
Thanks
Fritz
